name: Build on raspberry

# This workflow is triggered on pushes to the repository.
on: push

jobs:
  # clean:
  #   name: Clean
  #   runs-on: self-hosted
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  build:
    name: Build
    needs: clean
    runs-on: self-hosted
    steps:
      # Checkout
      - uses: actions/checkout@v2
      #   id: hello
      - name: Build
        run: |
          mkdir build && cd build
          cmake .. && make
      - name: Update PiCam
        run: |
          rm -rf /home/pi/picam
          mkdir /home/pi/picam
          cp ./build/pi_cam /home/pi/picam
          cp -R ./data /home/pi/picam